# Generated by Django 6.1.1 on 2026-09-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('crm', '0002_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.company', verbose_name='Компания сотрудника'),
        ),
    ]
